export const list = [
    "All",
    "Telugu",
    "Comedy",
    "Action",
    "Drama",
    "Horror",
    "Romantic",
    "Thriller",
    "Scifi",
    "Fantasy",
    "Crime",
    "Mystery",
    "Adventure",
    "Animation",
    "Biography",
    "Documentary",
    "Family",
    "History",
    "Music",
    "Musical",
    "Sport",
    "War",
    "Western",
    "All",
    "Telugu",
    "Comedy",
    "Action",
    "Drama",
    "Horror",
    "Romantic",
    "Thriller",
    "Scifi",
  ];

  export const LIVE_CHART_COUNT=20;